packages:
  - packages/*
  - packages/app/*
  - docs
  - test
allowBuilds:
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - rolldown
  - sharp
  - unrs-resolver

packageConfigs:
  "@hls-downloader/docs":
    overrides:
      "vite": "^8.0.0"