packages:
  - packages/*
  - packages/app/*
  - docs
  - test
allowBuilds:
  esbuild: true
  sharp: true
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - esbuild
  - rolldown
  - sharp
  - unrs-resolver
